#!/bin/bash

# 1) Database properties file.
# 2) SQL script file.
#
# Author: Denis Lussier.
# Author: Andres Gomez.

MY_CLASSPATH="../../target/benchmarksql-4.2.0-SNAPSHOT-jar-with-dependencies.jar"

MY_PROPERTIES="-Dprop=${1}"

java -cp .:${MY_CLASSPATH} ${MY_PROPERTIES} com.github.benchmarksql.jtpcc.jTPCC
